main:
  - name: Home
    url: /
    weight: 10

  - name: Research
    url: /research/
    weight: 20

  - name: People
    url: /people/
    weight: 30

  - name: Publications
    url: /publication/
    weight: 40

  - name: News
    url: /post/
    weight: 50

  - name: Get Involved
    url: /get-involved/
    weight: 60
